In [1]:
import sys
sys.path.insert(0, '..')
#for local import of parent dict

import scanpy as sc
import pandas as pd
import numpy as np
import pathlib
import scipy
from sklearn.decomposition import PCA

import seaborn as sns
import matplotlib.pyplot as plt

from ggml.plot import plot_heatmap, hier_clustering, plot_emb, plot_ellipses
from ggml.generator import get_pointcloud
from tqdm import tqdm

import ot

from ggml.benchmark import knn_from_dists, plot_table, plot_1split
import pickle

5.660704928275037e-15

/home/kuehn/anaconda3/envs/ggml/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#Define path and computed datasets
results_path = "/home/kuehn/ot_metric_learning/damin-ggml/data/results/clustering/paper"
computed_datasets = ["synth_2D_synth_200D_allmethods.pickle","kidney_full.pickle","breastcancer_full.pickle","myocard_infarct.pickle"] #,"synth_2D_synth_200D_breastcancer_full.pickle"]

#Define order of methods and which metrics you want to display/hide. (e.g. clustering or classification)
method_col = ['Euclidean', 'Manhatten', 'Cosine', 'LMNN', 'LFDA', 'NCA', 'ITML','GGML','GGML_L2'] #metrics.keys()
hide_metrics = ["KNN"]

In [3]:
results = {}
for d in computed_datasets:
    with open(f"{results_path}/{d}", 'rb') as handle:
            res = pickle.load(handle)
            print(res)
            results = results | res

{'synth_2D': {'GGML': {'global': {'KNN': '0.93±0.00', 'MI': np.float64(0.5021853144982367), 'ARI': 0.4298134835997084, 'VI': np.float64(1.1876646819153862)}, 'ground': {'KNN': '0.96±0.05', 'MI': np.float64(1.0986122886681096), 'ARI': 1.0, 'VI': np.float64(4.440892098500626e-16)}}, 'Euclidean': {'global': {'KNN': '0.32±0.01', 'MI': np.float64(0.00010647796277080124), 'ARI': -0.0005644254830748265, 'VI': np.float64(2.1939674727597325)}, 'ground': {'KNN': '0.29±0.10', 'MI': np.float64(0.0), 'ARI': -0.07288790723357261, 'VI': np.float64(2.1875122640133333)}}, 'Manhatten': {'global': {'KNN': '0.34±0.01', 'MI': np.float64(0.00010411256965139892), 'ARI': -0.0005489336363136319, 'VI': np.float64(2.1876480649227004)}, 'ground': {'KNN': '0.29±0.10', 'MI': np.float64(0.0), 'ARI': -0.07288790723357261, 'VI': np.float64(2.1875122640133333)}}, 'Cosine': {'global': {'KNN': '0.47±0.01', 'MI': np.float64(0.06077970714904078), 'ARI': 0.027264419445940942, 'VI': np.float64(2.4524658956164567)}, 'ground': {'KNN': '0.27±0.06', 'MI': np.float64(0.1078887003751345), 'ARI': 0.026175305665576028, 'VI': np.float64(1.8311328986593984)}}, 'LMNN': {'global': {'KNN': '0.93±0.00', 'MI': np.float64(0.009641290249009338), 'ARI': 0.006983928258700831, 'VI': np.float64(2.1343463398855445)}, 'ground': {'KNN': '0.43±0.10', 'MI': np.float64(0.007022218703138933), 'ARI': -0.06206025617896446, 'VI': np.float64(2.140992071123094)}}, 'LFDA': {'global': {'KNN': '0.42±0.01', 'MI': np.float64(0.06910509304420398), 'ARI': 0.03398946776180546, 'VI': np.float64(1.9122123024402546)}, 'ground': {'KNN': '0.33±0.13', 'MI': np.float64(0.05883806952464861), 'ARI': -0.017821422076741224, 'VI': np.float64(2.04908141060338)}}, 'NCA': {'global': {'KNN': '0.55±0.02', 'MI': np.float64(0.005551758196091661), 'ARI': 0.004870764179320227, 'VI': np.float64(2.1733921893987347)}, 'ground': {'KNN': '0.27±0.08', 'MI': np.float64(0.010320875185920453), 'ARI': -0.06001091107474086, 'VI': np.float64(2.146115799280836)}}, 'ITML': {'global': {'KNN': '0.48±0.01', 'MI': np.float64(0.1343152571147006), 'ARI': 0.08721938484520886, 'VI': np.float64(1.8368529351023033)}, 'ground': {'KNN': '0.36±0.07', 'MI': np.float64(0.1955577335417925), 'ARI': 0.043328409650418516, 'VI': np.float64(1.6049979001790424)}}}, 'synth_200D': {'GGML': {'global': {'KNN': '0.91±0.00', 'MI': np.float64(0.6769083254473607), 'ARI': 0.6115285478334747, 'VI': np.float64(0.8510943490129541)}, 'ground': {'KNN': '1.00±0.00', 'MI': np.float64(1.0986122886681096), 'ARI': 1.0, 'VI': np.float64(4.440892098500626e-16)}}, 'Euclidean': {'global': {'KNN': '0.74±0.03', 'MI': np.float64(0.0), 'ARI': -0.0006573672441870309, 'VI': np.float64(2.187512264013332)}, 'ground': {'KNN': '0.39±0.11', 'MI': np.float64(0.0), 'ARI': -0.06941431670281996, 'VI': np.float64(2.1535324566542546)}}, 'Manhatten': {'global': {'KNN': '0.67±0.03', 'MI': np.float64(0.0), 'ARI': -0.0006573672441870309, 'VI': np.float64(2.187512264013332)}, 'ground': {'KNN': '0.40±0.11', 'MI': np.float64(0.0), 'ARI': -0.07288790723357261, 'VI': np.float64(2.1875122640133333)}}, 'Cosine': {'global': {'KNN': '0.48±0.01', 'MI': np.float64(0.3142318989330168), 'ARI': 0.0007913618609141864, 'VI': np.float64(3.007375675272754)}, 'ground': {'KNN': '0.32±0.08', 'MI': np.float64(0.07441785657100017), 'ARI': -0.002229654403567447, 'VI': np.float64(1.240916414358075)}}, 'LMNN': {'global': {'KNN': '0.93±0.00', 'MI': np.float64(0.0040166855419039305), 'ARI': 0.00481807219712191, 'VI': np.float64(1.775076910869163)}, 'ground': {'KNN': '0.49±0.11', 'MI': np.float64(0.019748987093550024), 'ARI': -0.05153690410454629, 'VI': np.float64(2.1480142898262327)}}, 'LFDA': {'global': {'KNN': '0.32±0.01', 'MI': np.float64(0.0010107654033459069), 'ARI': 0.00014909471348828652, 'VI': np.float64(2.135894420665888)}, 'ground': {'KNN': '0.42±0.05', 'MI': np.float64(0.0673627792070544), 'ARI': -0.0017978682419416978, 'VI': np.float64(1.3526211204749314)}}, 'NCA': {'global': {'KNN': '0.92±0.01', 'MI': np.float64(0.00626603627975833), 'ARI': 0.007761774673079415, 'VI': np.float64(1.7708403673403599)}, 'ground': {'KNN': '0.47±0.11', 'MI': np.float64(0.04587137627908125), 'ARI': -0.023655516540380707, 'VI': np.float64(2.1021429135471514)}}, 'ITML': {'global': {'KNN': '0.39±0.01', 'MI': np.float64(0.017756024651435123), 'ARI': 0.001778026129852794, 'VI': np.float64(2.101358167114487)}, 'ground': {'KNN': '0.35±0.11', 'MI': np.float64(0.076238564353943), 'ARI': -0.001794526693584567, 'VI': np.float64(1.626522374380039)}}}}
{'kidney_full': {'GGML_L2': {'global': {'KNN': '0.70±0.04', 'MI': np.float64(0.14473181333266497), 'ARI': 0.09827152883770499, 'VI': np.float64(1.8264847845424106)}, 'ground': {'KNN': '0.86±0.03', 'MI': np.float64(0.7743757499830455), 'ARI': 0.8068295363709033, 'VI': np.float64(0.34004314702831406)}}, 'Euclidean': {'global': {'KNN': '0.52±0.06', 'MI': np.float64(0.18375309606347617), 'ARI': 0.003958123438006975, 'VI': np.float64(3.1701019193091926)}, 'ground': {'KNN': '0.56±0.10', 'MI': np.float64(0.06843621236719634), 'ARI': 0.020977413619431996, 'VI': np.float64(1.1107756617986255)}}, 'Manhatten': {'global': {'KNN': '0.53±0.06', 'MI': np.float64(0.15356019619628278), 'ARI': 0.00901777858932898, 'VI': np.float64(3.119501121912417)}, 'ground': {'KNN': '0.61±0.06', 'MI': np.float64(0.06843621236719634), 'ARI': 0.020977413619431996, 'VI': np.float64(1.1107756617986255)}}, 'Cosine': {'global': {'KNN': '0.50±0.06', 'MI': np.float64(0.17617703004137103), 'ARI': 0.00048566499136894296, 'VI': np.float64(3.0902388772809233)}, 'ground': {'KNN': '0.59±0.06', 'MI': np.float64(0.06843621236719634), 'ARI': 0.020977413619431996, 'VI': np.float64(1.1107756617986255)}}, 'LFDA': {'global': {'KNN': '0.55±0.04', 'MI': np.float64(0.043763627854949444), 'ARI': -0.009986683364930367, 'VI': np.float64(2.7374798670813227)}, 'ground': {'KNN': '0.76±0.13', 'MI': np.float64(0.04568256642465274), 'ARI': -0.014044177802017999, 'VI': np.float64(1.391540875496919)}}, 'ITML': {'global': {'KNN': '0.46±0.04', 'MI': np.float64(0.0367533711400363), 'ARI': 0.0009058430349799362, 'VI': np.float64(2.4655731990572445)}, 'ground': {'KNN': '0.50±0.14', 'MI': np.float64(0.06352449657421685), 'ARI': 0.005930522139208983, 'VI': np.float64(1.2736145428968508)}}}}
{'breastcancer_full': {'GGML_L2': {'global': {'KNN': '0.72±0.04', 'MI': np.float64(0.061487614609357776), 'ARI': 0.06302418899124948, 'VI': np.float64(1.6143695558690714)}, 'ground': {'KNN': '0.83±0.03', 'MI': np.float64(0.2116928153988329), 'ARI': 0.48978722992520635, 'VI': np.float64(0.7870871842336341)}}, 'Euclidean': {'global': {'KNN': '0.69±0.04', 'MI': np.float64(0.11468872642221771), 'ARI': -0.00228732086438654, 'VI': np.float64(2.8694075788960514)}, 'ground': {'KNN': '0.72±0.06', 'MI': np.float64(0.005752650353818181), 'ARI': -0.01784707871501033, 'VI': np.float64(0.6822083366887368)}}, 'Manhatten': {'global': {'KNN': '0.69±0.06', 'MI': np.float64(0.058903683626318266), 'ARI': 0.02276074061932953, 'VI': np.float64(2.3310604715914893)}, 'ground': {'KNN': '0.72±0.03', 'MI': np.float64(0.03295602416732052), 'ARI': 0.13044225859567693, 'VI': np.float64(0.926904356546989)}}, 'Cosine': {'global': {'KNN': '0.70±0.03', 'MI': np.float64(0.10564214790871555), 'ARI': 0.02666336174076584, 'VI': np.float64(2.905249821434097)}, 'ground': {'KNN': '0.71±0.07', 'MI': np.float64(0.005752650353818181), 'ARI': -0.01784707871501033, 'VI': np.float64(0.6822083366887368)}}, 'LFDA': {'global': {'KNN': '0.66±0.06', 'MI': np.float64(0.036015190267314375), 'ARI': 0.05766487483862875, 'VI': np.float64(2.4742818072442923)}, 'ground': {'KNN': '0.74±0.03', 'MI': np.float64(0.059903063190708344), 'ARI': 0.1275075922836734, 'VI': np.float64(0.6838411820223423)}}, 'ITML': {'global': {'KNN': '0.68±0.05', 'MI': np.float64(0.022000793915429338), 'ARI': 0.0355179388104063, 'VI': np.float64(2.271945650519157)}, 'ground': {'KNN': '0.69±0.06', 'MI': np.float64(0.005752650353818181), 'ARI': -0.01784707871501033, 'VI': np.float64(0.6822083366887368)}}}}
{'myocard_infarct_full': {'GGML': {'global': {'KNN': None, 'MI': np.float64(0.06588260969479365), 'ARI': 0.05190391563357253, 'VI': np.float64(2.8324531924552936)}, 'ground': {'KNN': None, 'MI': np.float64(0.8199560956672625), 'ARI': 0.8334700574241182, 'VI': np.float64(0.412326974959901)}}, 'Euclidean': {'global': {'KNN': None, 'MI': np.float64(0.2913945106656455), 'ARI': 0.11239601771914384, 'VI': np.float64(2.8254061442532623)}, 'ground': {'KNN': None, 'MI': np.float64(0.11033632461054577), 'ARI': 0.01819341826339295, 'VI': np.float64(1.2082230259369948)}}, 'Manhatten': {'global': {'KNN': None, 'MI': np.float64(0.26919683670875066), 'ARI': 0.11265576705623875, 'VI': np.float64(2.250646909244304)}, 'ground': {'KNN': None, 'MI': np.float64(0.21655771999995202), 'ARI': 0.16859783078474552, 'VI': np.float64(0.9957802351581824)}}, 'Cosine': {'global': {'KNN': None, 'MI': np.float64(0.32948305936949757), 'ARI': 0.09385763662292057, 'VI': np.float64(3.4002299737790023)}, 'ground': {'KNN': None, 'MI': np.float64(0.07110885802533673), 'ARI': 0.003014633951566212, 'VI': np.float64(1.1869955097129823)}}, 'LFDA': {'global': {'KNN': None, 'MI': np.float64(0.5061597004855214), 'ARI': 0.6410730450202237, 'VI': np.float64(0.7122914279209941)}, 'ground': {'KNN': None, 'MI': np.float64(0.6442227645066465), 'ARI': 0.5309932001365224, 'VI': np.float64(0.7492032694188908)}}, 'ITML': {'global': {'KNN': None, 'MI': np.float64(0.06951945492173522), 'ARI': 0.005459770789388584, 'VI': np.float64(2.7650899225762195)}, 'ground': {'KNN': None, 'MI': np.float64(0.09091412828468812), 'ARI': 0.027331350196649964, 'VI': np.float64(1.1473849691942812)}}, 'GGML_L2': {'global': {'KNN': None, 'MI': np.float64(0.6282682655791063), 'ARI': 0.7052155698589267, 'VI': np.float64(0.8119656350251614)}, 'ground': {'KNN': None, 'MI': np.float64(0.9117644159648715), 'ARI': 0.9199295274658813, 'VI': np.float64(0.20496703152982243)}}}}

In [ ]:

results_ground_cols = {(d,s):[] for d in results.keys() for s in next(iter(results[d].values()))["ground"].keys() if s not in hide_metrics }
results_global_cols = {(d,s):[] for d in results.keys() for s in next(iter(results[d].values()))["global"].keys() if s not in hide_metrics}

for d in results:
    for m in method_col: #results[d]:
        if m in results[d]:
            for s in results[d][m]["ground"]:
                if s not in hide_metrics:
                    results_ground_cols[(d,s)].append(f"{results[d][m]["ground"][s]:.2f}")
            for s in results[d][m]["global"]:
                if s not in hide_metrics:
                    results_global_cols[(d,s)].append(f"{results[d][m]["global"][s]:.2f}")  
        else:
            #If values were not compute input "--"
            for s in next(iter(results[d].values()))["ground"].keys():
                if s not in hide_metrics:
                    results_ground_cols[(d,s)].append("--")
                    results_global_cols[(d,s)].append("--")   

results_ground_cols["method"] = method_col 
results_global_cols["method"] = method_col 


plot_table(pd.DataFrame(results_ground_cols))
plot_table(pd.DataFrame(results_global_cols))

,"(synth_2D, MI)","(synth_2D, ARI)","(synth_2D, VI)","(synth_200D, MI)","(synth_200D, ARI)","(synth_200D, VI)","(kidney_full, MI)","(kidney_full, ARI)","(kidney_full, VI)","(breastcancer_full, MI)","(breastcancer_full, ARI)","(breastcancer_full, VI)","(myocard_infarct_full, MI)","(myocard_infarct_full, ARI)","(myocard_infarct_full, VI)"
method,,,,,,,,,,,,,,,
Euclidean,0.00,-0.07,2.19,0.00,-0.07,2.15,0.07,0.02,1.11,0.01,-0.02,0.68,0.11,0.02,1.21
Manhatten,0.00,-0.07,2.19,0.00,-0.07,2.19,0.07,0.02,1.11,0.03,0.13,0.93,0.22,0.17,1.00
Cosine,0.11,0.03,1.83,0.07,-0.00,1.24,0.07,0.02,1.11,0.01,-0.02,0.68,0.07,0.00,1.19
LMNN,0.01,-0.06,2.14,0.02,-0.05,2.15,--,--,--,--,--,--,--,--,--
LFDA,0.06,-0.02,2.05,0.07,-0.00,1.35,0.05,-0.01,1.39,0.06,0.13,0.68,0.64,0.53,0.75
NCA,0.01,-0.06,2.15,0.05,-0.02,2.10,--,--,--,--,--,--,--,--,--
ITML,0.20,0.04,1.60,0.08,-0.00,1.63,0.06,0.01,1.27,0.01,-0.02,0.68,0.09,0.03,1.15
GGML,1.10,1.00,0.00,1.10,1.00,0.00,--,--,--,--,--,--,0.82,0.83,0.41
GGML_L2,--,--,--,--,--,--,0.77,0.81,0.34,0.21,0.49,0.79,0.91,0.92,0.20

\begin{tabular}{llllllllllllllll}
\toprule
 & ('synth_2D', 'MI') & ('synth_2D', 'ARI') & ('synth_2D', 'VI') & ('synth_200D', 'MI') & ('synth_200D', 'ARI') & ('synth_200D', 'VI') & ('kidney_full', 'MI') & ('kidney_full', 'ARI') & ('kidney_full', 'VI') & ('breastcancer_full', 'MI') & ('breastcancer_full', 'ARI') & ('breastcancer_full', 'VI') & ('myocard_infarct_full', 'MI') & ('myocard_infarct_full', 'ARI') & ('myocard_infarct_full', 'VI') \\
method &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
Euclidean & 0.00 & -0.07 & 2.19 & 0.00 & -0.07 & 2.15 & 0.07 & 0.02 & 1.11 & 0.01 & -0.02 & 0.68 & 0.11 & 0.02 & 1.21 \\
Manhatten & 0.00 & -0.07 & 2.19 & 0.00 & -0.07 & 2.19 & 0.07 & 0.02 & 1.11 & 0.03 & 0.13 & 0.93 & 0.22 & 0.17 & 1.00 \\
Cosine & 0.11 & 0.03 & 1.83 & 0.07 & -0.00 & 1.24 & 0.07 & 0.02 & 1.11 & 0.01 & -0.02 & 0.68 & 0.07 & 0.00 & 1.19 \\
LMNN & 0.01 & -0.06 & 2.14 & 0.02 & -0.05 & 2.15 & -- & -- & -- & -- & -- & -- & -- & -- & -- \\
LFDA & 0.06 & -0.02 & 2.05 & 0.07 & -0.00 & 1.35 & 0.05 & -0.01 & 1.39 & 0.06 & 0.13 & 0.68 & 0.64 & 0.53 & 0.75 \\
NCA & 0.01 & -0.06 & 2.15 & 0.05 & -0.02 & 2.10 & -- & -- & -- & -- & -- & -- & -- & -- & -- \\
ITML & 0.20 & 0.04 & 1.60 & 0.08 & -0.00 & 1.63 & 0.06 & 0.01 & 1.27 & 0.01 & -0.02 & 0.68 & 0.09 & 0.03 & 1.15 \\
GGML & 1.10 & 1.00 & 0.00 & 1.10 & 1.00 & 0.00 & -- & -- & -- & -- & -- & -- & 0.82 & 0.83 & 0.41 \\
GGML_L2 & -- & -- & -- & -- & -- & -- & 0.77 & 0.81 & 0.34 & 0.21 & 0.49 & 0.79 & 0.91 & 0.92 & 0.20 \\
\bottomrule
\end{tabular}

,"(synth_2D, MI)","(synth_2D, ARI)","(synth_2D, VI)","(synth_200D, MI)","(synth_200D, ARI)","(synth_200D, VI)","(kidney_full, MI)","(kidney_full, ARI)","(kidney_full, VI)","(breastcancer_full, MI)","(breastcancer_full, ARI)","(breastcancer_full, VI)","(myocard_infarct_full, MI)","(myocard_infarct_full, ARI)","(myocard_infarct_full, VI)"
method,,,,,,,,,,,,,,,
Euclidean,0.00,-0.00,2.19,0.00,-0.00,2.19,0.18,0.00,3.17,0.11,-0.00,2.87,0.29,0.11,2.83
Manhatten,0.00,-0.00,2.19,0.00,-0.00,2.19,0.15,0.01,3.12,0.06,0.02,2.33,0.27,0.11,2.25
Cosine,0.06,0.03,2.45,0.31,0.00,3.01,0.18,0.00,3.09,0.11,0.03,2.91,0.33,0.09,3.40
LMNN,0.01,0.01,2.13,0.00,0.00,1.78,--,--,--,--,--,--,--,--,--
LFDA,0.07,0.03,1.91,0.00,0.00,2.14,0.04,-0.01,2.74,0.04,0.06,2.47,0.51,0.64,0.71
NCA,0.01,0.00,2.17,0.01,0.01,1.77,--,--,--,--,--,--,--,--,--
ITML,0.13,0.09,1.84,0.02,0.00,2.10,0.04,0.00,2.47,0.02,0.04,2.27,0.07,0.01,2.77
GGML,0.50,0.43,1.19,0.68,0.61,0.85,--,--,--,--,--,--,0.07,0.05,2.83
GGML_L2,--,--,--,--,--,--,0.14,0.10,1.83,0.06,0.06,1.61,0.63,0.71,0.81

\begin{tabular}{llllllllllllllll}
\toprule
 & ('synth_2D', 'MI') & ('synth_2D', 'ARI') & ('synth_2D', 'VI') & ('synth_200D', 'MI') & ('synth_200D', 'ARI') & ('synth_200D', 'VI') & ('kidney_full', 'MI') & ('kidney_full', 'ARI') & ('kidney_full', 'VI') & ('breastcancer_full', 'MI') & ('breastcancer_full', 'ARI') & ('breastcancer_full', 'VI') & ('myocard_infarct_full', 'MI') & ('myocard_infarct_full', 'ARI') & ('myocard_infarct_full', 'VI') \\
method &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
Euclidean & 0.00 & -0.00 & 2.19 & 0.00 & -0.00 & 2.19 & 0.18 & 0.00 & 3.17 & 0.11 & -0.00 & 2.87 & 0.29 & 0.11 & 2.83 \\
Manhatten & 0.00 & -0.00 & 2.19 & 0.00 & -0.00 & 2.19 & 0.15 & 0.01 & 3.12 & 0.06 & 0.02 & 2.33 & 0.27 & 0.11 & 2.25 \\
Cosine & 0.06 & 0.03 & 2.45 & 0.31 & 0.00 & 3.01 & 0.18 & 0.00 & 3.09 & 0.11 & 0.03 & 2.91 & 0.33 & 0.09 & 3.40 \\
LMNN & 0.01 & 0.01 & 2.13 & 0.00 & 0.00 & 1.78 & -- & -- & -- & -- & -- & -- & -- & -- & -- \\
LFDA & 0.07 & 0.03 & 1.91 & 0.00 & 0.00 & 2.14 & 0.04 & -0.01 & 2.74 & 0.04 & 0.06 & 2.47 & 0.51 & 0.64 & 0.71 \\
NCA & 0.01 & 0.00 & 2.17 & 0.01 & 0.01 & 1.77 & -- & -- & -- & -- & -- & -- & -- & -- & -- \\
ITML & 0.13 & 0.09 & 1.84 & 0.02 & 0.00 & 2.10 & 0.04 & 0.00 & 2.47 & 0.02 & 0.04 & 2.27 & 0.07 & 0.01 & 2.77 \\
GGML & 0.50 & 0.43 & 1.19 & 0.68 & 0.61 & 0.85 & -- & -- & -- & -- & -- & -- & 0.07 & 0.05 & 2.83 \\
GGML_L2 & -- & -- & -- & -- & -- & -- & 0.14 & 0.10 & 1.83 & 0.06 & 0.06 & 1.61 & 0.63 & 0.71 & 0.81 \\
\bottomrule
\end{tabular}